import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "@/styles/main.scss";

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body className={raleway.variable}>{children}</body>
    </html>
  );
}
